import { useEffect } from 'react'
import { useLocation } from 'react-router-dom'

// ============================================================
// usePageTitle — Auto-set document title based on current route
// ============================================================

const TITLES = {
  '/': 'VibeSwap — Swap',
  '/buy': 'Buy / Sell — VibeSwap',
  '/trade': 'Trading — VibeSwap',
  '/earn': 'Pools — VibeSwap',
  '/vault': 'Vaults — VibeSwap',
  '/send': 'Bridge — VibeSwap',
  '/lend': 'Lending — VibeSwap',
  '/stake': 'Staking — VibeSwap',
  '/perps': 'Perpetuals — VibeSwap',
  '/options': 'Options — VibeSwap',
  '/yield': 'Yield — VibeSwap',
  '/dca': 'DCA — VibeSwap',
  '/bonds': 'Bonds — VibeSwap',
  '/insurance': 'Insurance — VibeSwap',
  '/aggregator': 'Aggregator — VibeSwap',
  '/launchpad': 'Launchpad — VibeSwap',
  '/intent-market': 'Intent Market — VibeSwap',
  '/nft': 'NFTs — VibeSwap',
  '/predict': 'Predictions — VibeSwap',
  '/gameswap': 'GameSwap — VibeSwap',
  '/portfolio': 'Portfolio — VibeSwap',
  '/history': 'Activity — VibeSwap',
  '/rewards': 'Rewards — VibeSwap',
  '/wallet': 'Wallet — VibeSwap',
  '/notifications': 'Notifications — VibeSwap',
  '/settings': 'Settings — VibeSwap',
  '/profile': 'Profile — VibeSwap',
  '/leaderboard': 'Leaderboard — VibeSwap',
  '/referral': 'Referrals — VibeSwap',
  '/tutorial': 'Getting Started — VibeSwap',
  '/gas': 'Gas Tracker — VibeSwap',
  '/jarvis': 'JARVIS — VibeSwap',
  '/voice': 'Voice Chat — VibeSwap',
  '/mesh': 'Mind Mesh — VibeSwap',
  '/agents': 'AI Agents — VibeSwap',
  '/depin': 'DePIN — VibeSwap',
  '/rwa': 'RWA Hub — VibeSwap',
  '/infofi': 'InfoFi — VibeSwap',
  '/memehunter': 'Memehunter — VibeSwap',
  '/feed': 'VibeFeed — VibeSwap',
  '/forum': 'Forum — VibeSwap',
  '/board': 'Discussions — VibeSwap',
  '/wiki': 'Wiki — VibeSwap',
  '/live': 'Live — VibeSwap',
  '/govern': 'Governance — VibeSwap',
  '/bounties': 'Bounties — VibeSwap',
  '/docs': 'Docs — VibeSwap',
  '/whitepaper': 'Whitepaper — VibeSwap',
  '/research': 'Research — VibeSwap',
  '/philosophy': 'Philosophy — VibeSwap',
  '/economics': 'Economics — VibeSwap',
  '/tokenomics': 'Tokenomics — VibeSwap',
  '/gametheory': 'Game Theory — VibeSwap',
  '/commit-reveal': 'Commit-Reveal — VibeSwap',
  '/covenants': 'Covenants — VibeSwap',
  '/rosetta': 'Rosetta — VibeSwap',
  '/trust': 'Trust — VibeSwap',
  '/jul': 'JUL — VibeSwap',
  '/agentic': 'Agentic Economy — VibeSwap',
  '/inversion': 'Graceful Inversion — VibeSwap',
  '/privacy': 'Privacy — VibeSwap',
  '/api': 'API Docs — VibeSwap',
  '/contact': 'Contact — VibeSwap',
  '/ecosystem': 'Ecosystem — VibeSwap',
  '/brand': 'Brand Assets — VibeSwap',
  '/status': 'Status — VibeSwap',
  '/analytics': 'Analytics — VibeSwap',
  '/oracle': 'Oracle — VibeSwap',
  '/circuit-breaker': 'Circuit Breaker — VibeSwap',
  '/crosschain': 'Cross-Chain — VibeSwap',
  '/security': 'Security — VibeSwap',
  '/roadmap': 'Roadmap — VibeSwap',
  '/team': 'Team — VibeSwap',
  '/faq': 'FAQ — VibeSwap',
  '/changelog': 'Changelog — VibeSwap',
  '/about': 'About — VibeSwap',
  '/mine': 'Mine — VibeSwap',
  '/fairness': 'Fairness — VibeSwap',
  '/personality': 'Identity — VibeSwap',
  '/prompts': 'Prompts — VibeSwap',
  '/apps': 'App Store — VibeSwap',
  '/abstraction': 'Abstraction — VibeSwap',
  '/wheel': 'Medicine Wheel — VibeSwap',
  '/partners': 'Partners — VibeSwap',
  '/legal': 'Legal — VibeSwap',
  '/careers': 'Careers — VibeSwap',
  '/badges': 'Badges — VibeSwap',
  '/alerts': 'Alerts — VibeSwap',
  '/export': 'Export — VibeSwap',
  '/multisend': 'Multi-Send — VibeSwap',
  '/limit': 'Limit Orders — VibeSwap',
  '/airdrop': 'Airdrop — VibeSwap',
  '/staking-rewards': 'Staking Rewards — VibeSwap',
  '/watchlist': 'Watchlist — VibeSwap',
  '/onramp': 'Buy Crypto — VibeSwap',
  '/proposals': 'Proposals — VibeSwap',
  '/proposal': 'Proposal — VibeSwap',
  '/farming': 'Liquidity Mining — VibeSwap',
  '/portfolio-analytics': 'Portfolio Analytics — VibeSwap',
  '/bridge-history': 'Bridge History — VibeSwap',
  '/treasury': 'Treasury — VibeSwap',
  '/otc': 'OTC Desk — VibeSwap',
  '/fees': 'Fee Tiers — VibeSwap',
  '/social': 'Social Trading — VibeSwap',
  '/achievements': 'Achievements — VibeSwap',
  '/swap-history': 'Swap History — VibeSwap',
  '/grants': 'Grants — VibeSwap',
  '/lp-positions': 'LP Positions — VibeSwap',
  '/networks': 'Networks — VibeSwap',
  '/approvals': 'Approvals — VibeSwap',
  '/markets': 'Markets — VibeSwap',
  '/create-token': 'Token Creator — VibeSwap',
  '/derivatives': 'Derivatives — VibeSwap',
  '/dao-tools': 'DAO Tools — VibeSwap',
  '/margin': 'Margin Trading — VibeSwap',
  '/automation': 'Automation — VibeSwap',
  '/revenue': 'Revenue Share — VibeSwap',
  '/vesting': 'Vesting — VibeSwap',
  '/liquidations': 'Liquidations — VibeSwap',
  '/delegate': 'Delegate — VibeSwap',
  '/migrate': 'Migration — VibeSwap',
  '/competitions': 'Competitions — VibeSwap',
  '/streaks': 'Streaks — VibeSwap',
  '/health': 'Protocol Health — VibeSwap',
  '/fee-calculator': 'Fee Calculator — VibeSwap',
  '/mev': 'MEV Dashboard — VibeSwap',
  '/contributors': 'Contributors — VibeSwap',
  '/multichain': 'Multi-Chain — VibeSwap',
  '/education': 'Education — VibeSwap',
  '/price-impact': 'Price Impact — VibeSwap',
  '/backtest': 'Backtester — VibeSwap',
  '/snapshot': 'Snapshots — VibeSwap',
  '/tax': 'Tax Reports — VibeSwap',
  '/referral-dashboard': 'Referral Dashboard — VibeSwap',
  '/screener': 'DEX Screener — VibeSwap',
  '/offramp': 'Sell Crypto — VibeSwap',
  '/whales': 'Whale Watcher — VibeSwap',
  '/rebalance': 'Rebalancer — VibeSwap',
  '/lp-optimizer': 'LP Optimizer — VibeSwap',
  '/claims': 'Airdrop Claims — VibeSwap',
  '/sentiment': 'Sentiment — VibeSwap',
  '/priority': 'Priority Auction — VibeSwap',
  '/compare': 'Protocol Comparison — VibeSwap',
  '/arbitrage': 'Arbitrage — VibeSwap',
  '/contracts': 'Smart Contracts — VibeSwap',
  '/unlocks': 'Token Unlocks — VibeSwap',
  '/names': '.vibe Names — VibeSwap',
}

export function usePageTitle(customTitle) {
  const location = useLocation()

  useEffect(() => {
    const title = customTitle || TITLES[location.pathname] || 'VibeSwap'
    document.title = title
  }, [location.pathname, customTitle])
}
