import { useEffect } from 'react'
import { useLocation } from 'react-router-dom'

// ============================================================
// usePageTitle — Auto-set document title based on current route
// ============================================================

const TITLES = {
  '/': 'VibeSwap — Swap',
  '/buy': 'Buy / Sell — VibeSwap',
  '/trade': 'Trading — VibeSwap',
  '/earn': 'Pools — VibeSwap',
  '/vault': 'Vaults — VibeSwap',
  '/send': 'Bridge — VibeSwap',
  '/lend': 'Lending — VibeSwap',
  '/stake': 'Staking — VibeSwap',
  '/perps': 'Perpetuals — VibeSwap',
  '/options': 'Options — VibeSwap',
  '/yield': 'Yield — VibeSwap',
  '/dca': 'DCA — VibeSwap',
  '/bonds': 'Bonds — VibeSwap',
  '/insurance': 'Insurance — VibeSwap',
  '/aggregator': 'Aggregator — VibeSwap',
  '/launchpad': 'Launchpad — VibeSwap',
  '/nft': 'NFTs — VibeSwap',
  '/predict': 'Predictions — VibeSwap',
  '/gameswap': 'GameSwap — VibeSwap',
  '/portfolio': 'Portfolio — VibeSwap',
  '/history': 'Activity — VibeSwap',
  '/rewards': 'Rewards — VibeSwap',
  '/wallet': 'Wallet — VibeSwap',
  '/notifications': 'Notifications — VibeSwap',
  '/settings': 'Settings — VibeSwap',
  '/profile': 'Profile — VibeSwap',
  '/leaderboard': 'Leaderboard — VibeSwap',
  '/referral': 'Referrals — VibeSwap',
  '/tutorial': 'Getting Started — VibeSwap',
  '/gas': 'Gas Tracker — VibeSwap',
  '/jarvis': 'JARVIS — VibeSwap',
  '/voice': 'Voice Chat — VibeSwap',
  '/mesh': 'Mind Mesh — VibeSwap',
  '/agents': 'AI Agents — VibeSwap',
  '/depin': 'DePIN — VibeSwap',
  '/rwa': 'RWA Hub — VibeSwap',
  '/infofi': 'InfoFi — VibeSwap',
  '/memehunter': 'Memehunter — VibeSwap',
  '/feed': 'VibeFeed — VibeSwap',
  '/forum': 'Forum — VibeSwap',
  '/board': 'Discussions — VibeSwap',
  '/wiki': 'Wiki — VibeSwap',
  '/live': 'Live — VibeSwap',
  '/govern': 'Governance — VibeSwap',
  '/bounties': 'Bounties — VibeSwap',
  '/docs': 'Docs — VibeSwap',
  '/whitepaper': 'Whitepaper — VibeSwap',
  '/research': 'Research — VibeSwap',
  '/philosophy': 'Philosophy — VibeSwap',
  '/economics': 'Economics — VibeSwap',
  '/tokenomics': 'Tokenomics — VibeSwap',
  '/gametheory': 'Game Theory — VibeSwap',
  '/commit-reveal': 'Commit-Reveal — VibeSwap',
  '/covenants': 'Covenants — VibeSwap',
  '/rosetta': 'Rosetta — VibeSwap',
  '/trust': 'Trust — VibeSwap',
  '/jul': 'JUL — VibeSwap',
  '/agentic': 'Agentic Economy — VibeSwap',
  '/inversion': 'Graceful Inversion — VibeSwap',
  '/privacy': 'Privacy — VibeSwap',
  '/api': 'API Docs — VibeSwap',
  '/contact': 'Contact — VibeSwap',
  '/ecosystem': 'Ecosystem — VibeSwap',
  '/brand': 'Brand Assets — VibeSwap',
  '/status': 'Status — VibeSwap',
  '/analytics': 'Analytics — VibeSwap',
  '/oracle': 'Oracle — VibeSwap',
  '/circuit-breaker': 'Circuit Breaker — VibeSwap',
  '/crosschain': 'Cross-Chain — VibeSwap',
  '/security': 'Security — VibeSwap',
  '/roadmap': 'Roadmap — VibeSwap',
  '/team': 'Team — VibeSwap',
  '/faq': 'FAQ — VibeSwap',
  '/changelog': 'Changelog — VibeSwap',
  '/about': 'About — VibeSwap',
  '/mine': 'Mine — VibeSwap',
  '/fairness': 'Fairness — VibeSwap',
  '/personality': 'Identity — VibeSwap',
  '/prompts': 'Prompts — VibeSwap',
  '/apps': 'App Store — VibeSwap',
  '/abstraction': 'Abstraction — VibeSwap',
  '/wheel': 'Medicine Wheel — VibeSwap',
}

export function usePageTitle(customTitle) {
  const location = useLocation()

  useEffect(() => {
    const title = customTitle || TITLES[location.pathname] || 'VibeSwap'
    document.title = title
  }, [location.pathname, customTitle])
}
