#!/usr/bin/env node
/**
 * Persistance Script
 * Forces cache invalidation across Vercel and browsers
 *
 * Usage: npm run persistance
 *
 * What it does:
 * 1. Updates build metadata with current timestamp
 * 2. Touches index.html to force Vercel rebuild
 * 3. Updates cache-bust query param in critical files
 * 4. Logs all changes for verification
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const timestamp = Date.now();
const buildId = `v${timestamp}`;

console.log('🔄 PERSISTANCE: Forcing cache invalidation...\n');

// 1. Update build metadata file
const buildMetaPath = path.join(rootDir, 'src', 'utils', 'buildMeta.js');
const buildMetaContent = `// Auto-generated by persistance script - DO NOT EDIT
// Last update: ${new Date().toISOString()}
export const BUILD_ID = '${buildId}';
export const BUILD_TIMESTAMP = ${timestamp};
export const BUILD_DATE = '${new Date().toISOString()}';
`;

fs.writeFileSync(buildMetaPath, buildMetaContent);
console.log(`✓ Updated build metadata: ${buildId}`);

// 2. Touch index.html to force Vercel to recognize changes
const indexPath = path.join(rootDir, 'index.html');
let indexContent = fs.readFileSync(indexPath, 'utf8');

// Update or add build comment
const buildComment = `<!-- Build: ${buildId} -->`;
if (indexContent.includes('<!-- Build:')) {
  indexContent = indexContent.replace(/<!-- Build: [^>]+ -->/, buildComment);
} else {
  indexContent = indexContent.replace('<!DOCTYPE html>', `<!DOCTYPE html>\n${buildComment}`);
}

fs.writeFileSync(indexPath, indexContent);
console.log(`✓ Updated index.html with build marker`);

// 3. Update vercel.json to ensure no caching of HTML
const vercelPath = path.join(rootDir, 'vercel.json');
const vercelConfig = {
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "buildCommand": "npm run build",
  "outputDirectory": "dist",
  "framework": "vite",
  "headers": [
    {
      "source": "/assets/(.*)",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "public, max-age=31536000, immutable"
        }
      ]
    },
    {
      "source": "/(.*)",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "no-cache, no-store, must-revalidate"
        },
        {
          "key": "Pragma",
          "value": "no-cache"
        },
        {
          "key": "Expires",
          "value": "0"
        }
      ]
    }
  ]
};

fs.writeFileSync(vercelPath, JSON.stringify(vercelConfig, null, 2) + '\n');
console.log(`✓ Updated vercel.json with strict no-cache headers`);

// 4. Summary
console.log('\n📋 PERSISTANCE COMPLETE');
console.log('─'.repeat(40));
console.log(`Build ID:    ${buildId}`);
console.log(`Timestamp:   ${new Date().toISOString()}`);
console.log('');
console.log('Next steps:');
console.log('1. Commit and push changes');
console.log('2. Vercel will auto-deploy with new cache headers');
console.log('3. Users should hard-refresh (Ctrl+Shift+R) once');
console.log('');
