// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/ReentrancyGuardUpgradeable.sol";

/**
 * @title AbsorptionRegistry — On-Chain Attribution for Absorbed Protocols
 * @notice Tracks every protocol absorbed into VSOS, credits original developers,
 *         and ensures Shapley-fair rewards flow back to creators.
 *
 * @dev Philosophy: Convergence, not conquest.
 *
 *   Every absorbed protocol is recorded on-chain with:
 *     - Source attribution (protocol name, original authors, license)
 *     - Files absorbed and modifications made
 *     - Usage metrics for Shapley reward computation
 *     - Placeholder escrow links for unclaimed developer rewards
 *
 *   "Every protocol on this list solved a real problem. Then they put a
 *    tollbooth in front of the solution. We remove the tollbooth and
 *    replace it with math."
 *
 *   The Lawson Fairness Floor guarantees every absorbed protocol earns
 *   at minimum 1% of the value their code generates — regardless of scale.
 */
contract AbsorptionRegistry is
    OwnableUpgradeable,
    UUPSUpgradeable,
    ReentrancyGuardUpgradeable
{
    // ============ Constants ============

    /// @notice Lawson Fairness Floor — minimum 1% attribution regardless of usage
    uint256 public constant FAIRNESS_FLOOR_BPS = 100; // 1%

    // ============ Structs ============

    struct AbsorbedProtocol {
        bytes32 protocolId;
        string name;                // e.g., "AAVE", "Chainlink", "Synthetix"
        string sourceRepo;          // Original GitHub/source URL
        string license;             // e.g., "MIT", "GPL-3.0", "BUSL-1.1"
        string[] filesAbsorbed;     // List of files/patterns absorbed
        string modifications;       // Description of what we changed
        bytes32[] developerIds;     // PlaceholderEscrow identity hashes
        uint256 absorbedAt;
        uint256 usageCount;         // How many times absorbed code was invoked
        uint256 valueGenerated;     // VIBE value generated by this absorbed code
        uint256 rewardsDistributed; // VIBE distributed to original devs
        bool active;
    }

    struct Developer {
        bytes32 identityHash;       // PlaceholderEscrow identity hash
        string platform;            // "github", "twitter", etc.
        string username;            // Platform username
        bytes32[] protocols;        // Protocols this dev contributed to
    }

    // ============ State ============

    /// @notice All absorbed protocols
    mapping(bytes32 => AbsorbedProtocol) public protocols;
    bytes32[] public allProtocols;

    /// @notice Developer registry (maps to PlaceholderEscrow)
    mapping(bytes32 => Developer) public developers;
    bytes32[] public allDevelopers;

    /// @notice Contract → protocol mapping (which absorbed code powers which contract)
    mapping(address => bytes32[]) public contractSources;

    /// @notice Authorized usage recorders
    mapping(address => bool) public recorders;

    // ============ Events ============

    event ProtocolAbsorbed(
        bytes32 indexed protocolId,
        string name,
        string sourceRepo,
        uint256 developerCount
    );

    event DeveloperCredited(
        bytes32 indexed protocolId,
        bytes32 indexed developerId,
        string platform,
        string username
    );

    event UsageRecorded(
        bytes32 indexed protocolId,
        address indexed sourceContract,
        uint256 valueGenerated
    );

    event RewardsAttributed(
        bytes32 indexed protocolId,
        uint256 amount
    );

    event RecorderUpdated(address indexed recorder, bool authorized);

    // ============ Errors ============

    error Unauthorized();
    error AlreadyAbsorbed();
    error ProtocolNotFound();
    error ZeroValue();

    // ============ Initializer ============

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    function initialize(address _owner) external initializer {
        __Ownable_init(_owner);
        __UUPSUpgradeable_init();
        __ReentrancyGuard_init();
    }

    // ============ Admin ============

    function setRecorder(address recorder, bool authorized) external onlyOwner {
        recorders[recorder] = authorized;
        emit RecorderUpdated(recorder, authorized);
    }

    // ============ Protocol Absorption ============

    /**
     * @notice Record the absorption of an external protocol
     * @param name Protocol name (e.g., "AAVE")
     * @param sourceRepo Original source repository URL
     * @param license Original license
     * @param filesAbsorbed List of files/patterns absorbed
     * @param modifications Description of changes made
     * @param developerPlatforms Platforms of original developers
     * @param developerUsernames Usernames of original developers
     * @return protocolId The protocol's unique identifier
     */
    function absorbProtocol(
        string calldata name,
        string calldata sourceRepo,
        string calldata license,
        string[] calldata filesAbsorbed,
        string calldata modifications,
        string[] calldata developerPlatforms,
        string[] calldata developerUsernames
    ) external onlyOwner returns (bytes32 protocolId) {
        require(
            developerPlatforms.length == developerUsernames.length,
            "Platform/username length mismatch"
        );

        protocolId = keccak256(abi.encodePacked(name, sourceRepo));

        if (protocols[protocolId].absorbedAt != 0) revert AlreadyAbsorbed();

        // Register developers
        bytes32[] memory devIds = new bytes32[](developerPlatforms.length);
        for (uint256 i = 0; i < developerPlatforms.length; i++) {
            bytes32 devId = keccak256(
                abi.encodePacked(developerPlatforms[i], ":", developerUsernames[i])
            );
            devIds[i] = devId;

            if (developers[devId].identityHash == bytes32(0)) {
                developers[devId] = Developer({
                    identityHash: devId,
                    platform: developerPlatforms[i],
                    username: developerUsernames[i],
                    protocols: new bytes32[](0)
                });
                allDevelopers.push(devId);
            }
            developers[devId].protocols.push(protocolId);

            emit DeveloperCredited(protocolId, devId, developerPlatforms[i], developerUsernames[i]);
        }

        protocols[protocolId] = AbsorbedProtocol({
            protocolId: protocolId,
            name: name,
            sourceRepo: sourceRepo,
            license: license,
            filesAbsorbed: filesAbsorbed,
            modifications: modifications,
            developerIds: devIds,
            absorbedAt: block.timestamp,
            usageCount: 0,
            valueGenerated: 0,
            rewardsDistributed: 0,
            active: true
        });

        allProtocols.push(protocolId);

        emit ProtocolAbsorbed(protocolId, name, sourceRepo, devIds.length);
    }

    // ============ Usage Tracking ============

    /**
     * @notice Record usage of absorbed protocol code
     * @dev Called by VSOS contracts when absorbed code executes
     * @param protocolId The absorbed protocol
     * @param sourceContract The contract that used the absorbed code
     * @param valueGenerated VIBE value generated by this invocation
     */
    function recordUsage(
        bytes32 protocolId,
        address sourceContract,
        uint256 valueGenerated
    ) external {
        if (!recorders[msg.sender] && msg.sender != owner()) revert Unauthorized();

        AbsorbedProtocol storage proto = protocols[protocolId];
        if (proto.absorbedAt == 0) revert ProtocolNotFound();

        proto.usageCount++;
        proto.valueGenerated += valueGenerated;

        // Track which contract uses which protocol
        bytes32[] storage sources = contractSources[sourceContract];
        bool found = false;
        for (uint256 i = 0; i < sources.length; i++) {
            if (sources[i] == protocolId) { found = true; break; }
        }
        if (!found) sources.push(protocolId);

        emit UsageRecorded(protocolId, sourceContract, valueGenerated);
    }

    /**
     * @notice Record rewards distributed to absorbed protocol developers
     * @param protocolId The protocol whose developers received rewards
     * @param amount VIBE amount distributed
     */
    function recordRewards(bytes32 protocolId, uint256 amount) external {
        if (!recorders[msg.sender] && msg.sender != owner()) revert Unauthorized();
        if (amount == 0) revert ZeroValue();

        AbsorbedProtocol storage proto = protocols[protocolId];
        if (proto.absorbedAt == 0) revert ProtocolNotFound();

        proto.rewardsDistributed += amount;
        emit RewardsAttributed(protocolId, amount);
    }

    // ============ Link Contract to Protocol ============

    /**
     * @notice Declare that a VSOS contract uses code from an absorbed protocol
     * @param vsosContract The VSOS contract address
     * @param protocolId The absorbed protocol it uses
     */
    function linkContract(address vsosContract, bytes32 protocolId) external onlyOwner {
        if (protocols[protocolId].absorbedAt == 0) revert ProtocolNotFound();

        bytes32[] storage sources = contractSources[vsosContract];
        for (uint256 i = 0; i < sources.length; i++) {
            if (sources[i] == protocolId) return; // already linked
        }
        sources.push(protocolId);
    }

    // ============ View Functions ============

    function getProtocol(bytes32 protocolId)
        external view returns (
            string memory name,
            string memory sourceRepo,
            string memory license,
            uint256 absorbedAt,
            uint256 usageCount,
            uint256 valueGenerated,
            uint256 rewardsDistributed,
            uint256 developerCount
        )
    {
        AbsorbedProtocol storage p = protocols[protocolId];
        return (
            p.name, p.sourceRepo, p.license,
            p.absorbedAt, p.usageCount, p.valueGenerated,
            p.rewardsDistributed, p.developerIds.length
        );
    }

    function getDeveloper(bytes32 developerId)
        external view returns (
            string memory platform,
            string memory username,
            uint256 protocolCount
        )
    {
        Developer storage d = developers[developerId];
        return (d.platform, d.username, d.protocols.length);
    }

    function protocolCount() external view returns (uint256) {
        return allProtocols.length;
    }

    function developerCount() external view returns (uint256) {
        return allDevelopers.length;
    }

    function getContractSources(address vsosContract)
        external view returns (bytes32[] memory)
    {
        return contractSources[vsosContract];
    }

    // ============ UUPS ============

    function _authorizeUpgrade(address newImplementation) internal override onlyOwner {
        require(newImplementation.code.length > 0, "Not a contract");
    }
}
