#!/usr/bin/env bash
# TRP Round Summary Generator
# Generates a pre-filled round summary from the template in TRP_RUNNER.md.
#
# Usage: ./scripts/trp-round-gen.sh <round_number> [target_contract]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ -z "${1:-}" ]; then
    echo "Usage: trp-round-gen.sh <round_number> [target_contract]"
    exit 1
fi
ROUND="$1"
TARGET="${2:-TBD}"

# Validate round is numeric
if ! [[ "$ROUND" =~ ^[0-9]+$ ]]; then
    echo "ERROR: Round must be numeric, got: $ROUND"
    exit 1
fi
SUMMARIES_DIR="$REPO_ROOT/docs/trp/round-summaries"
OUTPUT="$SUMMARIES_DIR/round-${ROUND}.md"
HEATMAP="$REPO_ROOT/docs/trp/efficiency-heatmap.md"

# Check if round already exists
if [ -f "$OUTPUT" ]; then
    echo "ERROR: round-${ROUND}.md already exists. Delete it first to regenerate."
    exit 1
fi

mkdir -p "$SUMMARIES_DIR"

# Find previous round summary for open items
PREV_ROUND=$((ROUND - 1))
PREV_FILE="$SUMMARIES_DIR/round-${PREV_ROUND}.md"

# Get current tier from last round or default
CURRENT_TIER="49"  # Updated to R53 state
if [ -f "$PREV_FILE" ]; then
    tier=$(grep -oP 'Tier \K\d+' "$PREV_FILE" 2>/dev/null | tail -1 || true)
    CURRENT_TIER="${tier:-$CURRENT_TIER}"
fi

# Get current git state
COMMIT=$(git -C "$REPO_ROOT" rev-parse --short HEAD)
DATE=$(date +%Y-%m-%d)

# Extract open items from previous round (if exists)
OPEN_ITEMS=""
if [ -f "$PREV_FILE" ]; then
    OPEN_ITEMS=$(sed -n '/^## Open Items/,/^---/p' "$PREV_FILE" 2>/dev/null | head -20 || echo "No previous round summary found.")
fi

# Extract current heatmap status
HEATMAP_STATUS=""
if [ -f "$HEATMAP" ]; then
    HEATMAP_STATUS=$(grep -E '^\|.*\|.*\|.*\|.*\|' "$HEATMAP" | grep -v "Contract\|---" || echo "No heatmap data.")
fi

# Generate the round summary
cat > "$OUTPUT" << EOF
# TRP Round ${ROUND} — ${TARGET}

**Date**: ${DATE}
**Baseline**: Tier ${CURRENT_TIER}
**Commit**: ${COMMIT}
**Target**: ${TARGET}
**Progression**: Tier ${CURRENT_TIER} → Tier $((CURRENT_TIER + 1))

---

## Pre-Round Heat Map

${HEATMAP_STATUS}

## Prior Open Items (from R${PREV_ROUND})

${OPEN_ITEMS}

---

## Scoring

| Dimension | Metric | Score |
|-----------|--------|-------|
| **Survival** | | PASS |
| **R0 (density)** | | |
| **R1 (adversarial)** | | |
| **R2 (knowledge)** | | |
| **R3 (capability)** | | |
| **R4 (cure)** | | /  |
| **Efficiency** | See block below | |
| **Integration** | | YES/NO |

**Overall Grade: **

---

## R4: Cures Applied

| Finding | Severity | Fix | Status |
|---------|----------|-----|--------|
| | | | CLOSED/OPEN |

## R1: Observations

(Findings from adversarial review)

---

## Test Results

| Suite | Result |
|-------|--------|
| | /  pass |

---

## Efficiency Block (v3.0)

\`\`\`yaml
efficiency:
  agents_spawned: 0
  agent_tiers:
    opus: 0
    sonnet: 0
    haiku: 0
  contracts_in_scope: 0
  contracts_skipped: 0
  findings_new: 0
  findings_closed: 0
  closure_rate: 0%
  yield: 0
  heat_map_changes: ""
\`\`\`

---

## Open Items (Updated)

### CRITICAL
(none)

### HIGH
(none)

### MEDIUM
| ID | Contract | Description | Round |
|----|----------|-------------|-------|
| AMM-07 | VibeAMM | Fee path inconsistency (input vs output) | R37 |

---

*Generated by TRP Runner v3.0 — round-gen.sh*
EOF

echo "Generated: $OUTPUT"
echo ""
echo "Next steps:"
echo "  1. Fill in target and findings"
echo "  2. Run: ./scripts/trp-regression.sh --quick"
echo "  3. Execute TRP loops"
echo "  4. Fill in scoring and efficiency block"
echo "  5. Update heatmap: docs/trp/efficiency-heatmap.md"
