// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IComputeSubsidy
 * @notice Interface for the Reputation-Weighted Compute Subsidy System
 *
 * Pricing AI agents in the VibeSwap network:
 *   1 JOULE = X FLOP-seconds of compute energy
 *   Agents spend JOULE to execute tasks
 *   Higher reputation → lower effective cost (up to 90% subsidy)
 *   Revenue clawback replenishes the subsidy pool
 *   Staked reputation enables temporary boosts for high-stakes tasks
 */
interface IComputeSubsidy {
    // ============ Enums ============

    enum JobStatus { PENDING, ACTIVE, COMPLETED, FAILED, DISPUTED }

    // ============ Structs ============

    /// @notice A compute job submitted by an agent
    struct ComputeJob {
        bytes32 jobId;
        address agent;                  // Agent operator address
        uint256 agentId;               // AgentRegistry ID
        uint256 baseCost;              // Base JOULE cost before subsidy
        uint256 subsidizedCost;        // Actual JOULE cost after subsidy
        uint256 subsidyAmount;         // JOULE covered by subsidy pool
        uint256 reputationAtSubmit;    // Snapshot of agent reputation
        uint256 stakedBoost;           // Extra JOULE staked for reputation boost
        JobStatus status;
        uint256 createdAt;
        uint256 completedAt;
        uint8 qualityRating;           // 0-100 post-task quality (set by rater)
        uint256 revenueGenerated;      // Revenue from this job (for clawback)
    }

    /// @notice Subsidy pool state
    struct SubsidyPool {
        uint256 totalFunded;           // Total JOULE ever deposited
        uint256 totalDisbursed;        // Total JOULE paid out as subsidies
        uint256 totalClawedBack;       // Total JOULE recovered from revenue
        uint256 balance;               // Current available JOULE in pool
    }

    /// @notice Agent compute profile
    struct AgentComputeProfile {
        uint256 totalJobsCompleted;
        uint256 totalJobsFailed;
        uint256 totalSubsidyReceived;
        uint256 totalRevenueGenerated;
        uint256 totalClawbackPaid;
        uint256 totalStaked;           // Currently staked for reputation boost
        uint256 effectiveReputation;   // Current reputation after boosts
        uint256 lastActivityAt;
    }

    // ============ Events ============

    event JobSubmitted(bytes32 indexed jobId, address indexed agent, uint256 baseCost, uint256 subsidizedCost, uint256 subsidyAmount);
    event JobCompleted(bytes32 indexed jobId, address indexed agent, uint8 qualityRating);
    event JobFailed(bytes32 indexed jobId, address indexed agent, uint256 stakeSlashed);
    event SubsidyDisbursed(bytes32 indexed jobId, address indexed agent, uint256 amount, uint256 reputationScore);
    event RevenueClawback(bytes32 indexed jobId, address indexed agent, uint256 revenueAmount, uint256 clawbackAmount);
    event ReputationStaked(address indexed agent, uint256 amount, uint256 newEffectiveRep);
    event ReputationUnstaked(address indexed agent, uint256 amount);
    event StakeSlashed(address indexed agent, uint256 amount, bytes32 indexed jobId);
    event PoolFunded(address indexed funder, uint256 amount);
    event SubsidyCurveUpdated(uint256 maxSubsidyBps);

    // ============ Errors ============

    error AgentNotRegistered();
    error AgentSuspended();
    error InsufficientJouleBalance();
    error InsufficientPoolBalance();
    error JobNotFound();
    error JobNotActive();
    error JobAlreadyCompleted();
    error InvalidRating();
    error NothingToUnstake();
    error NothingToClawback();
    error Unauthorized();
    error ZeroAmount();

    // ============ Core Functions ============

    /// @notice Submit a compute job. JOULE is charged at the subsidized rate.
    /// @param baseCost The base JOULE cost of the compute task
    /// @return jobId The unique job identifier
    function submitJob(uint256 baseCost) external returns (bytes32 jobId);

    /// @notice Complete a job and record quality rating
    /// @param jobId The job to complete
    /// @param qualityRating 0-100 quality score
    function completeJob(bytes32 jobId, uint8 qualityRating) external;

    /// @notice Mark a job as failed. Slashes staked reputation if any.
    /// @param jobId The job that failed
    function failJob(bytes32 jobId) external;

    /// @notice Report revenue generated by a completed job (triggers clawback)
    /// @param jobId The job that generated revenue
    /// @param revenueAmount Revenue in JOULE terms
    function reportRevenue(bytes32 jobId, uint256 revenueAmount) external;

    // ============ Staking ============

    /// @notice Stake JOULE to temporarily boost effective reputation
    /// @param amount JOULE to stake
    function stakeForReputation(uint256 amount) external;

    /// @notice Unstake JOULE (only if no active jobs with stake)
    /// @param amount JOULE to unstake
    function unstakeReputation(uint256 amount) external;

    // ============ Pool Management ============

    /// @notice Fund the subsidy pool with JOULE
    /// @param amount JOULE to deposit
    function fundPool(uint256 amount) external;

    // ============ View Functions ============

    /// @notice Calculate the subsidized cost for an agent
    /// @param agent Agent operator address
    /// @param baseCost Base JOULE cost
    /// @return subsidizedCost The cost after subsidy
    /// @return subsidyAmount The subsidy pool contribution
    function calculateSubsidy(address agent, uint256 baseCost) external view returns (uint256 subsidizedCost, uint256 subsidyAmount);

    /// @notice Get the subsidy multiplier for a reputation score (18 decimals)
    /// @param reputationScore 0-10000 reputation score
    /// @return multiplier Cost multiplier (1e18 = full price, 0.1e18 = 90% subsidy)
    function getSubsidyMultiplier(uint256 reputationScore) external pure returns (uint256 multiplier);

    /// @notice Get the clawback percentage for a given subsidy level
    /// @param subsidyBps Subsidy received in basis points
    /// @return clawbackBps Clawback percentage in basis points
    function getClawbackRate(uint256 subsidyBps) external pure returns (uint256 clawbackBps);

    /// @notice Get agent compute profile
    function getAgentProfile(address agent) external view returns (AgentComputeProfile memory);

    /// @notice Get job details
    function getJob(bytes32 jobId) external view returns (ComputeJob memory);

    /// @notice Get subsidy pool state
    function getPoolState() external view returns (SubsidyPool memory);

    /// @notice Get effective reputation for an agent (base + stake boost)
    function getEffectiveReputation(address agent) external view returns (uint256);
}
